name: Main Verification
run-name: Main Branch Protection for ${{ github.event.head_commit.message }}
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    protect-main:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: "25"
            
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v6
            
            - name: Make Gradle Executable
              run: chmod +x gradlew
            
            - name: Build Project
              run: ./gradlew build

            
